### ISSUE TITLE
Crash when opening link and closing before it loads

### ISSUE THREAD

**Issue by shikamaru12** [laurencedawson/reddit-sync-development#1019]
Sometimes if I click a link and find out it is a YouTube one, or not an imgur link, I immediately exit it due to limited bandwidth. However, 90% of the time he app freezes and then crashes as soon as I exit the link. This only happens when the link is loading and I exit it. This has been an issue for the past 2 versions.

**Comment by ikjadoon** [comment]
Fixed in v10.7.22; update via Google Play.

Also, was already reported: https://github.com/laurencedawson/reddit-sync-development/issues/990

**Comment by shikamaru12** [comment]
Oh, sorry about that. I didn't really know what I was doing, I'm not used
to Github.

**Comment by ikjadoon** [comment]
Oh, no, no, no, it's OK. :) Sorry, my reply was a bit terse. 

It's funny you posted this today; this bug has been going on for a while, but it *just* got fixed this morning, hehehe.

Nah, this app's GitHub is pretty chill. The only reason I know that bug is already reported is because I was the one who reported it, heheh.

**Comment by laurencedawson** [comment]
Merging with #990.
