### ISSUE TITLE
Vote percentage is gone after the 11.6.1 update

### ISSUE THREAD

**Issue by elmkzgirxp** [laurencedawson/reddit-sync-development#1262]

**Comment by machinator2** [comment]
I cannot reproduce this. Can you post a screenshot and a direct link to an example post?

**Comment by machinator2** [comment]
Also, what view are you using?

**Comment by muffinz** [comment]
[Sync for reddit v11.6.1 is now going live on Google Play](https://www.reddit.com/r/redditsync/comments/4v7g6w/sync_for_reddit_v1161_is_now_going_live_on_google/)
[Screenshot](http://imgur.com/a/0rWig)

Fixed height cards. View should not matter because vote percentage was only available while browsing the announcement; vote percentage was not visible in the actual card.

**Comment by machinator2** [comment]
It is there. It was just moved. Look at the top of the card, next to the subreddit name.

**Comment by muffinz** [comment]
Yes it's there. The change in position was missing in the release notes, so we assumed it was missing.

**Comment by machinator2** [comment]
Yeah, I can see where the confusion came from. I believe he moved it because on certain devices the upvote percentage was overlapping the upvote button.

**Comment by elmkzgirxp** [comment]
Yep, it is indeed moved. Thanks.
