### ISSUE TITLE
[Bug] Preview image in card posts disappear when opened, for non-image links

### ISSUE THREAD

**Issue by machinator2** [laurencedawson/reddit-sync-development#1474]
See thread: https://www.reddit.com/r/redditsync/comments/51y6od/preview_image_in_card_posts_disappears_when_post/

**Comment by amweiss** [comment]
Resetting advanced view settings fixes it for a while, seems like until I close the app. After that the described behavior returns.

**Comment by laurencedawson** [comment]
This isn't a bug. It's a per subreddit setting on how they want media previews to be displayed.

**Comment by amweiss** [comment]
Then the bug is that resetting the advanced view options ignores this setting. The behavior is inconsistent when resetting view settings as before resetting options http://www.reddit.com/r/truereddit/comments/56lbvg/_/ hides the image, but after, it displays. I prefer the images always appear, but I'd settle for consistency.

**Comment by laurencedawson** [comment]
This is still down to the media settings for that sub...
