### ISSUE TITLE
[Critical bug] The [Reply] FAB overlaps with the [>] comment navigation arrow (http://i.imgur.com/q9iCkNu.jpg)

### ISSUE THREAD

**Issue by okungnyo** [laurencedawson/reddit-sync-development#816]
http://i.imgur.com/q9iCkNu.jpg

**Comment by curiousgeorgie** [comment]
Although it goes away when you scroll down, it reappears if you hit the left comment arrow, which is more likely to be a time when you will soon want to use the right comment arrow (though it is also annoying sometimes when you scroll up then want to go to the next comment).

**Comment by Pranav14** [comment]
Instead of left and right buttons stretching horizontally across the screens, a more intuitive way to scroll through the vertical comments might be up and down buttons close to each other in the bottom left. This would avoid the overlap with the reply button. Bonus points if the navigation buttons were FAB.

**Comment by laurencedawson** [comment]
This has since been fixed. Cheers!
