### ISSUE TITLE
[Request] Per-subreddit default comment sort

### ISSUE THREAD

**Issue by m-p-3** [laurencedawson/reddit-sync-development#950]
I know it is possible to change the default comment sort in the app, but sometimes a specific sort type is more useful for a specific subreddit.

For example, the _Top_ sort is nice for the average subreddit, but the _Q&A_ sort works better for subreddits like /r/IAmA

If there was any way to make the comment sort stick per-subreddit, that'd be great!

**Comment by SharpMelon** [comment]
This is a feature that I've wanted to have in a reddit application for the longest time as I also have these habits of using different sorts for different subreddits. See example below:

* [New] /r/sweden
* [New] /r/bisexual
* [Hot] /r/gaming
* [Hot] /r/funny
* [Hot] /r/DIY

I spend a lot of time switching between sort modes since I am subbed to a lot of subreddits that I monitor frequently.

**Comment by laurencedawson** [comment]
Added to the backlog.

**Comment by laurencedawson** [comment]
This has since been added.
